#!/usr/bin/env bash
# client013-baseline-report.sh - generate client 013 (SAMSUNG) baseline report.
# Usage: bash ops/scripts/client013-baseline-report.sh
# Requires: stack up, indexer reachable (uses creds.env).
set -uo pipefail

ROOT=${MCT_STACK_ROOT:-/opt/mct-security-stack}
REPORT_DIR=${REPORT_DIR:-$ROOT/ops/reports}
CREDS=${CREDS:-/opt/wazuh-docker/multi-node/ops/creds.env}
TS=$(date +%Y%m%d-%H%M%S)
OUT="$REPORT_DIR/client013-baseline-$TS.md"
mkdir -p "$REPORT_DIR"

[ -f "$CREDS" ] && . "$CREDS" 2>/dev/null || true
API="https://127.0.0.1:55000"
IDX="https://127.0.0.1:9200"

TOKEN=$(curl -sk -u "wazuh-wui:${WAZUH_WUI_PASSWORD:-MyS3cr37P450r.*-}" "$API/security/user/authenticate" 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['data']['token'])" 2>/dev/null)

AGENT=$(curl -sk -H "Authorization: Bearer $TOKEN" "$API/agents?search=SAMSUNG" 2>/dev/null \
  | python3 -c "import json,sys; d=json.load(sys.stdin)['data']['affected_items']; print(json.dumps(d[0]))" 2>/dev/null)

VOL=$(curl -sk -u "admin:${WAZUH_ADMIN_PASSWORD:-}" "$IDX/wazuh-alerts-4.x-*/_search?size=0" -H "Content-Type: application/json" \
  -d '{"query":{"bool":{"filter":[{"term":{"agent.id":"013"}},{"range":{"timestamp":{"gte":"now-24h"}}}]}}}' 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null)

SYS=$(curl -sk -u "admin:${WAZUH_ADMIN_PASSWORD:-}" "$IDX/wazuh-alerts-4.x-*/_search?size=0" -H "Content-Type: application/json" \
  -d '{"query":{"bool":{"filter":[{"term":{"agent.id":"013"}},{"term":{"data.win.system.channel":"Microsoft-Windows-Sysmon/Operational"}},{"range":{"timestamp":{"gte":"now-24h"}}}]}}}' 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null)

HI=$(curl -sk -u "admin:${WAZUH_ADMIN_PASSWORD:-}" "$IDX/wazuh-alerts-4.x-*/_search?size=0" -H "Content-Type: application/json" \
  -d '{"query":{"bool":{"filter":[{"term":{"agent.id":"013"}},{"range":{"rule.level":{"gte":9}}}]}}}' 2>/dev/null \
  | python3 -c "import json,sys; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null)

cat > "$OUT" << EOF
# Client 013 Baseline Report

Date: $(date -u '+%Y-%m-%d %H:%M UTC')
Generated by: ops/scripts/client013-baseline-report.sh

## Agent

$AGENT

## Metrics (24h)

- Event volume: ${VOL:-?}
- Sysmon events: ${SYS:-?}
- Level >= 9 alerts: ${HI:-?}

## Notes

- Client-safe report; no internal paths/tooling names.
- Thresholds: coverage 100% required; level>=9 reviewed each cycle.
EOF
echo "Wrote $OUT"
